{
  "HTML": {
    "beautifiers": [
      "Pretty Diff",
      "JS-Beautify"
    ],
    "indent_inner_html": true,
    "indent_size": 4,
    "max_preserve_newlines": 1,
    "wrap_line_length": 100
  },
  "CSS": {
    "beautifiers": [
      "Prettier",
      "Pretty Diff",
      "JS-Beautify",
      "CSScomb"
    ],
    "indent_size": 4
  },
  "JSON": {
    "beautifiers": [
      "Prettier",
      "Pretty Diff",
      "JS-Beautify"
    ],
    "indent_size": 3
  },
  "JSON5": {
    "beautifiers": [
      "Prettier",
      "Pretty Diff",
      "JS-Beautify"
    ]
  },
  "JavaScript": {
    "beautifiers": [
      "Prettier",
      "Pretty Diff",
      "JS-Beautify",
      "ESLint"
    ],
    "indent_size": 4
  },
  "Java": {
    "beautifiers": [
      "Pretty Diff"
    ],
    "indent_size": 4
  },
  "PHP": {
    "beautifiers": [
      "PHP-CS-Fixer",
      "PHP_CodeSniffer"
    ]
  },
  "Python": {
    "beautifiers": [
      "Black",
      "YAPF"
    ]
  },
  "SCSS": {
    "beautifiers": [
      "Prettier",
      "Pretty Diff",
      "CSScomb"
    ]
  },
  "SQL": {
    "beautifiers": [
      "sqlformat"
    ]
  },
  "Sass": {
    "beautifiers": [
      "CSScomb"
    ]
  },
  "Vue": {
    "beautifiers": [
      "Prettier"
    ]
  },
  "TypeScript": {
    "beautifiers": [
      "Prettier",
      "Pretty Diff",
      "TSLint"
    ],
    "indent_size": 4
  },
  "C#": {
    "beautifiers": [
      "Pretty Diff"
    ],
    "indent_size": 3
  }
}